### ISSUE TITLE
BIGTOP-3.3.0 으로 refactoring

### ISSUE THREAD

**Issue by eubnara** [eubnara/dockerize-ambari#22]

**Comment by eubnara** [comment]
```
[ambari-server]  | TASK [./post/ambari-server : Setup jdbc for ambari] ****************************
[ambari-server]  | fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["ambari-server", "setup", "--jdbc-db=mysql", "--jdbc-driver=/usr/share/java/mysql-connector-java.jar"], "delta": "0:00:00.084543", "end": "2024-11-23 09:13:28.986942", "msg": "non-zero return code", "rc": 1, "start": "2024-11-23 09:13:28.902399", "stderr": "Traceback (most recent call last):\n  File \"/usr/sbin/ambari-server.py\", line 28, in <module>\n    from ambari_commons.exceptions import FatalException, NonFatalException\n  File \"/usr/lib/ambari-server/lib/ambari_commons/__init__.py\", line 21, in <module>\n    from ambari_commons.os_check import OSCheck, OSConst\n  File \"/usr/lib/ambari-server/lib/ambari_commons/os_check.py\", line 25, in <module>\n    import distro\nModuleNotFoundError: No module named 'distro'", "stderr_lines": ["Traceback (most recent call last):", "  File \"/usr/sbin/ambari-server.py\", line 28, in <module>", "    from ambari_commons.exceptions import FatalException, NonFatalException", "  File \"/usr/lib/ambari-server/lib/ambari_commons/__init__.py\", line 21, in <module>", "    from ambari_commons.os_check import OSCheck, OSConst", "  File \"/usr/lib/ambari-server/lib/ambari_commons/os_check.py\", line 25, in <module>", "    import distro", "ModuleNotFoundError: No module named 'distro'"], "stdout": "Using python  /usr/bin/python3\nSetup ambari-server", "stdout_lines": ["Using python  /usr/bin/python3", "Setup ambari-server"]}
[ambari-server]  | 
[ambari-server]  | PLAY RECAP *********************************************************************
[ambari-server]  | localhost                  : ok=6    changed=5    unreachable=0    failed=1    skipped=0    rescued=0    ignored=1   
[ambari-server]  | 
[ambari-server]  | Using python  /usr/bin/python3
[ambari-server]  | Starting ambari-server
[ambari-server]  | Traceback (most recent call last):
[ambari-server]  |   File "/usr/sbin/ambari-server.py", line 28, in <module>
[ambari-server]  |     from ambari_commons.exceptions import FatalException, NonFatalException
[ambari-server]  |   File "/usr/lib/ambari-server/lib/ambari_commons/__init__.py", line 21, in <module>
[ambari-server]  |     from ambari_commons.os_check import OSCheck, OSConst
[ambari-server]  |   File "/usr/lib/ambari-server/lib/ambari_commons/os_check.py", line 25, in <module>
[ambari-server]  |     import distro
[ambari-server]  | ModuleNotFoundError: No module named 'distro'
```

**Comment by eubnara** [comment]
```
2024-11-23 13:00:34,388 - The 'hadoop-hdfs-datanode' component did not advertise a version. This may indicate a problem with the component packaging. However, the stack-select tool was able to report a single version installed (3.4.0). This is the version that will be reported.
NoneType: None

The above exception was the cause of the following exception:

2024-11-23 13:00:36,003 - The 'hadoop-hdfs-datanode' component did not advertise a version. This may indicate a problem with the component packaging. However, the stack-select tool was able to report a single version installed (3.4.0). This is the version that will be reported.
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/BIGTOP/3.2.0/services/HDFS/package/scripts/datanode.py", line 173, in <module>
    DataNode().execute()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 354, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/BIGTOP/3.2.0/services/HDFS/package/scripts/datanode.py", line 53, in install
    self.install_packages(env)
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 875, in install_packages
    name = self.format_package_name(package['name'])
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 568, in format_package_name
    return self.get_package_from_available(name)
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 535, in get_package_from_available
    raise Fail("No package found for {0}(expected name: {1})".format(name, name_with_version))
resource_management.core.exceptions.Fail: No package found for hadoop_${stack_version}(expected name: hadoop_3_3_0)
```

- [ ] rpm 패키지명에 stack suffix 를 붙여 빌드하도록 변경하자.

**Comment by eubnara** [comment]
```
NoneType: None

The above exception was the cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/BIGTOP/3.2.0/services/YARN/package/scripts/application_timeline_server.py", line 98, in <module>
    ApplicationTimelineServer().execute()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 354, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/BIGTOP/3.2.0/services/YARN/package/scripts/application_timeline_server.py", line 43, in install
    self.install_packages(env)
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 875, in install_packages
    name = self.format_package_name(package['name'])
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 568, in format_package_name
    return self.get_package_from_available(name)
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 535, in get_package_from_available
    raise Fail("No package found for {0}(expected name: {1})".format(name, name_with_version))
resource_management.core.exceptions.Fail: No package found for ranger_${stack_version}-yarn-plugin(expected name: ranger_3_3_0-yarn-plugin)
```

- [ ] ranger 도 의존성이 있어 빌드를 해두어야할 것 같다.

**Comment by eubnara** [comment]
```
2024-11-24 05:57:12,527 - The 'hadoop-hdfs-datanode' component did not advertise a version. This may indicate a problem with the component packaging. However, the stack-select tool was able to report a single version installed (3.4.0). This is the version that will be reported.
2024-11-24 05:58:10,265 - The 'hadoop-hdfs-datanode' component did not advertise a version. This may indicate a problem with the component packaging. However, the stack-select tool was able to report a single version installed (3.4.0). This is the version that will be reported.
NoneType: None

The above exception was the cause of the following exception:

2024-11-24 05:58:10,623 - The 'hadoop-hdfs-datanode' component did not advertise a version. This may indicate a problem with the component packaging. However, the stack-select tool was able to report a single version installed (3.4.0). This is the version that will be reported.
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stack-hooks/after-INSTALL/scripts/hook.py", line 40, in <module>
    AfterInstallHook().execute()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 354, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stack-hooks/after-INSTALL/scripts/hook.py", line 33, in hook
    setup_stack_symlinks(self.stroutfile)
  File "/var/lib/ambari-agent/cache/stack-hooks/after-INSTALL/scripts/shared_initialization.py", line 67, in setup_stack_symlinks
    stack_select.select(package, json_version)
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/functions/stack_select.py", line 322, in select
    Execute(command, sudo=True)
  File "/usr/lib/ambari-agent/lib/resource_management/core/base.py", line 164, in __init__
    self.env.run()
  File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 163, in run
    self.run_action(resource, action)
  File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 127, in run_action
    provider_action()
  File "/usr/lib/ambari-agent/lib/resource_management/core/providers/system.py", line 270, in action_run
    shell.checked_call(self.resource.command, logoutput=self.resource.logoutput,
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 73, in inner
    result = function(command, **kwargs)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 100, in checked_call
    return _call_wrapper(command, logoutput=logoutput, throw_on_failure=True, stdout=stdout, stderr=stderr,
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 151, in _call_wrapper
    result = _call(command, **kwargs_copy)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 320, in _call
    raise ExecutionFailed(err_msg, code, out, err)
resource_management.core.exceptions.ExecutionFailed: Execution of 'ambari-python-wrap /usr/lib/bigtop-select/distro-select set hadoop-hdfs-datanode 3.4.0' returned 1. ERROR: Invalid version 3.4.0

Valid choices:
3.4.0
```
