### ISSUE TITLE
DataNode Install failed

### ISSUE THREAD

**Issue by eubnara** [eubnara/dockerize-ambari#4]
```
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stack-hooks/after-INSTALL/scripts/hook.py", line 39, in <module>
    AfterInstallHook().execute()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 352, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stack-hooks/after-INSTALL/scripts/hook.py", line 32, in hook
    setup_stack_symlinks(self.stroutfile)
  File "/var/lib/ambari-agent/cache/stack-hooks/after-INSTALL/scripts/shared_initialization.py", line 53, in setup_stack_symlinks
    stack_packages = stack_select.get_packages(stack_select.PACKAGE_SCOPE_INSTALL)
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/functions/stack_select.py", line 185, in get_packages
    raise Fail("The stack packages are not defined on the command. Unable to load packages for the stack-select tool")
resource_management.core.exceptions.Fail: The stack packages are not defined on the command. Unable to load packages for the stack-select tool
```

**Comment by eubnara** [comment]
https://github.com/apache/bigtop/blob/master/bigtop-packages/src/common/ambari/patch8-stack-hooks.diff 적용이 필요해 보인다. bigtop 이용해서 ambari 빌드 다시하여 rpm 교체가 필요하다.
